#ifndef __ERRORS_H__

#define __ERRORS_H__

#define CARS_OK 0
#define ERR_OPEN_FILE 1
#define ERR_READ_FILE_NAME 2
#define ERR_CLOSE_FILE 3
#define ERR_TOO_LONG_STR 4
#define ERR_TOO_LONG_BRAND 5
#define ERR_TOO_LONG_COUNTRY 6
#define ERR_TOO_LONG_COLOR 7
#define ERR_TOO_LONG_PRICE 8
#define ERR_TOO_LONG_CONDITION 9
#define ERR_TOO_LONG_WARRANTY 10
#define ERR_TOO_LONG_YEAR 11
#define ERR_TOO_LONG_MILEAGE 12
#define ERR_TOO_LONG_REPAIRS_NUM 13
#define ERR_TOO_LONG_OWNERS_NUM 14
#define ERR_READ_PRICE 15
#define ERR_WRONG_PRICE 16
#define ERR_WRONG_CONDITION 17
#define ERR_USED_WARRANTY 18
#define ERR_READ_WARRANTY 19
#define ERR_WRONG_WARRANTY 20
#define ERR_NEW_YEAR 21
#define ERR_READ_YEAR 22
#define ERR_WRONG_YEAR 23
#define ERR_NEW_MILEAGE 24
#define ERR_READ_MILEAGE 25
#define ERR_WRONG_MILEAGE 26
#define ERR_NEW_REPAIRS_NUM 27
#define ERR_READ_REPAIRS_NUM 28
#define ERR_WRONG_REPAIRS_NUM 29
#define ERR_NEW_OWNERS_NUM 30
#define ERR_READ_OWNERS_NUM 31
#define ERR_WRONG_OWNERS_NUM 32
#define ERR_NO_CARS 33
#define ERR_INCORRECT_PRICES 34
#define ERR_NO_RECORDS 35
#define ERR_WRONG_ACTION 36
#define ERR_READ_ACTION 37
#define ERR_EMPTY_FILE 38
#define ERR_INCORRECT_FILE 39
#define ERR_TOO_BIG_FILE 40

#endif
